// sveltekit-ts/src/components/add-gift-form.svelte
<script lang="ts">
	import { getGiftSchema } from '../schemas';
	import { upsertGifts } from '../services/gifts.service';
	import type { GiftInterface } from '../types';

	export let initialGift: GiftInterface;
	export let gifts: GiftInterface[];
	export let currentGift: GiftInterface;
	export let showForm: boolean;

	let submitted = false;
	let fields = { ...initialGift };

	const giftsSuggestions = ['Pantalla', 'Celular', 'Laptop', 'Audifonos'];
	const { giftSchema, textFieldRule, quantityFieldRule } = getGiftSchema();

	$: setFields(currentGift);

	function setFields(currentGift: GiftInterface) {
		fields = { ...currentGift };
	}

	function handleSubmit() {
		submitted = true;

		if (giftSchema.safeParse(fields).success) {
			const newGifts = upsertGifts(fields, gifts);

			localStorage.setItem('gifts', JSON.stringify(newGifts));
			gifts = newGifts;
			fields = { ...initialGift };
			submitted = false;
		}
	}
</script>

<form class="grid gap-4" on:submit|preventDefault={handleSubmit}>
	{#if showForm}
		<div class="grid gap-2">
			<div>
				<div class="flex items-center gap-x-2">
					<input
						type="text"
						placeholder="Agrega un regalo"
						bind:value={fields.name}
						class="flex-1 block w-full"
						name="name"
					/>
					<button
						on:click={() =>
							(fields.name = giftsSuggestions[Math.floor(Math.random() * giftsSuggestions.length)])}
						type="button"
					>
						Sorprenderme
					</button>
				</div>
				{#if submitted && !textFieldRule.safeParse(fields.name).success}
					<p class="error-message">El campo es requerido</p>
				{/if}
			</div>
			<div>
				<input
					type="text"
					placeholder="Url imagen"
					bind:value={fields.imageUrl}
					class="block w-full"
					name="imageUrl"
				/>
				{#if submitted && !textFieldRule.safeParse(fields.imageUrl).success}
					<p class="error-message">El campo es requerido</p>
				{/if}
			</div>
			<div>
				<input
					type="text"
					placeholder="Propietario"
					bind:value={fields.owner}
					class="block w-full"
					name="owner"
				/>
				{#if submitted && !textFieldRule.safeParse(fields.owner).success}
					<p class="error-message">El campo es requerido</p>
				{/if}
			</div>
			<div>
				<input
					type="number"
					placeholder="Precio"
					bind:value={fields.price}
					class="block w-full"
					name="price"
				/>
				{#if submitted && !quantityFieldRule.safeParse(fields.price).success}
					<p class="error-message">El numero debe ser un numero positivo</p>
				{/if}
			</div>
			<div>
				<input
					type="number"
					placeholder="Cantidad"
					bind:value={fields.quantity}
					class="block w-full"
					name="quantity"
				/>
				{#if submitted && !quantityFieldRule.safeParse(fields.quantity).success}
					<p class="error-message">El numero debe ser un entero positivo</p>
				{/if}
			</div>
		</div>
	{/if}
	<footer class={`flex ${showForm ? 'justify-between' : 'justify-center'}`}>
		<button type="button" class="primary" on:click={() => (showForm = !showForm)}>
			{showForm ? 'Cerrar' : 'Agregar regalo'}
		</button>
		{#if showForm}
			<button type="submit" class="primary">
				{fields.id ? 'Editar' : 'Agregar'}
			</button>
		{/if}
	</footer>
</form>

// denofresh/components/add-gift-form.tsx
import { Signal, useSignal } from '@preact/signals'
import { useEffect } from 'preact/hooks'
import { getGiftSchema } from '../schemas.ts'
import { upsertGifts } from '../services/gifts.service.ts'
import { GiftInterface } from '../types.ts'

interface PropsInterface {
  initialGift: GiftInterface
  currentGift: GiftInterface
  gifts: Signal<GiftInterface[]>
  showForm: Signal<boolean>
}

const { giftSchema, textFieldRule, quantityFieldRule } = getGiftSchema()
const giftsSuggestions = ['Pantalla', 'Celular', 'Laptop', 'Audifonos']

export default function AddGiftForm({
  initialGift,
  currentGift,
  gifts,
  showForm,
}: PropsInterface) {
  const fields = useSignal({ ...initialGift })
  const submitted = useSignal(false)

  useEffect(() => {
    fields.value = { ...currentGift }
  }, [currentGift])

  function handleChange(event: Event) {
    const { name, value } = event.target as HTMLInputElement

    fields.value = {
      ...fields.value,
      [name]: value,
    }
  }

  function handleSubmit(event: Event) {
    event.preventDefault()
    submitted.value = true

    const giftToSubmit: GiftInterface = {
      ...fields.value,
      quantity: Number(fields.value.quantity),
      price: Number(fields.value.price),
    }

    if (giftSchema.safeParse(giftToSubmit).success) {
      const newGifts = upsertGifts(giftToSubmit, gifts.value)

      localStorage.setItem('gifts', JSON.stringify(newGifts))
      gifts.value = newGifts
      fields.value = { ...initialGift }
      submitted.value = false
    }
  }

  return (
    <form className='grid gap-4' onSubmit={(event) => handleSubmit(event)}>
      {showForm.value &&
        (
          <div className='grid gap-2'>
            <div>
              <div className='flex items-center gap-x-2'>
                <input
                  className='block w-full flex-1'
                  name='name'
                  placeholder='Agrega un regalo'
                  type='text'
                  value={fields.value.name}
                  onInput={handleChange}
                />
                <button
                  type='button'
                  onClick={() => {
                    fields.value = {
                      ...fields.value,
                      name: giftsSuggestions[
                        Math.floor(Math.random() * giftsSuggestions.length)
                      ],
                    }
                  }}
                >
                  Sorprenderme
                </button>
              </div>
              {submitted.value &&
                !textFieldRule.safeParse(fields.value.name).success &&
                <p className='error-message'>El campo es requerido</p>}
            </div>
            <div>
              <input
                className='block w-full'
                name='imageUrl'
                placeholder='Url imagen'
                type='text'
                value={fields.value.imageUrl}
                onInput={handleChange}
              />
              {submitted.value &&
                !textFieldRule.safeParse(fields.value.imageUrl).success &&
                <p className='error-message'>El campo es requerido</p>}
            </div>
            <div>
              <input
                className='block w-full'
                name='owner'
                placeholder='Propietario'
                type='text'
                value={fields.value.owner}
                onInput={handleChange}
              />
              {submitted.value &&
                !textFieldRule.safeParse(fields.value.owner).success &&
                <p className='error-message'>El campo es requerido</p>}
            </div>
            <div>
              <input
                className='block w-full'
                name='price'
                placeholder='Precio'
                type='number'
                value={fields.value.price}
                onInput={handleChange}
              />
              {submitted.value &&
                !quantityFieldRule.safeParse(Number(fields.value.price))
                  .success &&
                (
                  <p className='error-message'>
                    El numero debe ser un numero positivo
                  </p>
                )}
            </div>
            <div>
              <input
                className='block w-full'
                name='quantity'
                placeholder='Cantidad'
                type='number'
                value={fields.value.quantity}
                onInput={handleChange}
              />
              {submitted.value &&
                !quantityFieldRule.safeParse(
                  Number(fields.value.quantity),
                )
                  .success &&
                (
                  <p className='error-message'>
                    El numero debe ser un entero positivo
                  </p>
                )}
            </div>
          </div>
        )}
      <footer
        className={`flex ${
          showForm.value ? 'justify-between' : 'justify-center'
        }`}
      >
        <button
          className='primary'
          type='button'
          onClick={() => {
            showForm.value = !showForm.value
          }}
        >
          {showForm.value ? 'Cerrar' : 'Agregar regalo'}
        </button>
        {showForm.value &&
          (
            <button className='primary' type='submit'>
              {fields.value.id ? 'Editar' : 'Agregar'}
            </button>
          )}
      </footer>
    </form>
  )
}
