// sveltekit-ts/src/components/gifts-list-summary.svelte
<script lang="ts">
	import type { GiftInterface } from '../types';

	export let gifts: GiftInterface[];
</script>

<footer class="pt-2 border-t border-gray-500">
	<p class="font-medium text-center">
		Total:
		{gifts
			.reduce((acc, curr) => {
				return acc + curr.price * curr.quantity;
			}, 0)
			.toLocaleString('es-ES', {
				style: 'currency',
				currency: 'EUR'
			})}
	</p>
</footer>

// vue-ts/src/components/gifts-list-summary.vue
<template>
  <footer class="pt-2 border-t border-gray-500" v-if="gifts.length">
    <p class="font-medium text-center">
      Total:
      {{
        gifts
          .reduce((acc, curr) => {
            return acc + curr.price * curr.quantity
          }, 0)
          .toLocaleString('es-ES', {
            style: 'currency',
            currency: 'EUR'
          })
      }}
    </p>
  </footer>
</template>

<script setup lang="ts">
import { GiftInterface } from '../types'

defineProps<{
  gifts: GiftInterface[]
}>()
</script>
