// nextjs-ts/src/app/components/gifts-list-item.tsx
/* eslint-disable @typescript-eslint/no-empty-function */
import type { GiftInterface } from "../types";

import { XMarkIcon } from "@heroicons/react/24/outline";
import { DocumentDuplicateIcon, PencilIcon } from "@heroicons/react/24/solid";

interface PropsInterface {
  gift: GiftInterface;
  anonymous?: boolean;
  setShowForm?: (value: boolean) => void;
  setCurrentGift?: (value: GiftInterface) => void;
  setGifts?: React.Dispatch<React.SetStateAction<GiftInterface[]>>;
}

export default function GiftsListItem({
  gift,
  anonymous = false,
  setCurrentGift = () => {},
  setShowForm = () => {},
  setGifts = () => {},
}: PropsInterface) {
  function handleDeleteGift() {
    setGifts((prevGifts: GiftInterface[]) => {
      const newGifts = prevGifts.filter(
        ({id: _id, owner: _owner}) => _id !== gift.id || _owner !== gift.owner,
      );

      localStorage.setItem("gifts", JSON.stringify(newGifts));

      return newGifts;
    });
  }

  return (
    <li className="flex items-center gap-x-12 rounded border border-gray-200 p-4 shadow-sm">
      <span className="flex flex-1 items-center gap-x-4">
        <img
          alt="imagen regalo"
          className="aspect-square size-14 rounded border border-pink-300 p-0.5"
          src={gift.imageUrl}
        />
        <div>
          <h3 className="font-medium">
            {gift.name} ({gift.quantity})
            {!anonymous && (
              <span>
                {" "}
                -{" "}
                {(gift.price * gift.quantity).toLocaleString("es-ES", {
                  style: "currency",
                  currency: "EUR",
                })}
              </span>
            )}
          </h3>
          <p className="text-lg">Propietario: {gift.owner || "No definido"}</p>
        </div>
      </span>
      {!anonymous && (
        <span className="flex items-center gap-x-2">
          <button
            aria-label="editar"
            className="secondary"
            type="button"
            onClick={() => {
              setCurrentGift({...gift});
              setShowForm(true);
            }}
          >
            <PencilIcon className="size-4 stroke-[4]" />
          </button>
          <button
            aria-label="duplicar"
            type="button"
            onClick={() => {
              setCurrentGift({
                ...gift,
                id: "",
                owner: "",
                quantity: 1,
              });
              setShowForm(true);
            }}
          >
            <DocumentDuplicateIcon className="size-4 stroke-[4]" />
          </button>
          <button aria-label="borrar" className="danger" type="button" onClick={handleDeleteGift}>
            <XMarkIcon className="size-4 stroke-[4]" />
          </button>
        </span>
      )}
    </li>
  );
}

// vue-ts/src/components/gifts-list-item.vue
<template>
  <li
    class="flex items-center p-4 border border-gray-200 rounded shadow-sm gap-x-12"
  >
    <span class="flex items-center flex-1 gap-x-4">
      <img
        :src="gift.imageUrl"
        alt="imagen regalo"
        class="p-0.5 border border-pink-300 rounded size-14 aspect-square"
      />
      <div>
        <h3 class="font-medium">
          {{ gift.name }} ({{ gift.quantity }})<span v-if="!anonymous">
            -
            {{
              (gift.price * gift.quantity).toLocaleString('es-ES', {
                style: 'currency',
                currency: 'EUR'
              })
            }}</span
          >
        </h3>
        <p class="text-lg">Propietario: {{ gift.owner || 'No definido' }}</p>
      </div>
    </span>
    <span class="flex items-center gap-x-2" v-if="!anonymous">
      <button
        class="secondary"
        @click="
          () => {
            currentGift = { ...gift }
            showForm = true
          }
        "
        aria-label="editar"
        type="button"
      >
        <PencilIcon class="stroke-[4] size-4" />
      </button>
      <button
        @click="
          () => {
            currentGift = {
              ...gift,
              id: '',
              owner: '',
              quantity: 1
            }
            showForm = true
          }
        "
        aria-label="duplicar"
        type="button"
      >
        <DocumentDuplicateIcon class="stroke-[4] size-4" />
      </button>
      <button
        class="danger"
        @click="handleDeleteGift"
        aria-label="borrar"
        type="button"
      >
        <XMarkIcon class="stroke-[4] size-4" />
      </button>
    </span>
  </li>
</template>

<script setup lang="ts">
import { XMarkIcon } from '@heroicons/vue/24/outline'
import { DocumentDuplicateIcon, PencilIcon } from '@heroicons/vue/24/solid'
import { GiftInterface } from '../types'

const { gift } = defineProps<{
  gift: GiftInterface
  anonymous?: boolean
}>()
const gifts = defineModel<GiftInterface[]>('gifts', {
  default: () => []
})
const currentGift = defineModel<GiftInterface>('currentGift')
const showForm = defineModel<boolean>('showForm')

function handleDeleteGift() {
  const newGifts = gifts.value.filter(
    ({ id: _id, owner: _owner }) => _id !== gift.id || _owner !== gift.owner
  )

  gifts.value = newGifts
  localStorage.setItem('gifts', JSON.stringify(newGifts))
}
</script>
