// vue-ts/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import api from './api'
import AddGiftForm from './components/add-gift-form.vue'
import GiftsListItem from './components/gifts-list-item.vue'
import GiftsListSummary from './components/gifts-list-summary.vue'
import { GiftInterface } from './types'

const INITIAL_GIFT: GiftInterface = {
  id: '',
  name: '',
  quantity: 1,
  imageUrl: '',
  owner: '',
  price: 0
}

const gifts = ref<GiftInterface[]>([])
const currentGift = ref<GiftInterface>({ ...INITIAL_GIFT })
const showForm = ref(false)
const loadingData = ref(false)
const showList = ref(false)

onMounted(async () => {
  loadingData.value = true
  gifts.value = await api.gifts.list()
  loadingData.value = false
})

function handleDeleteAllGifts() {
  gifts.value = []
  localStorage.removeItem('gifts')
}

function previewList() {
  window.scrollTo(0, 0)
  showList.value = true
}

function printList() {
  window.print()
}
</script>

<template>
  <dialog
    class="absolute top-0 grid w-full h-full bg-transparent shadow-xl text-neutral-900 place-content-center"
    v-if="showList"
  >
    <div class="flex flex-col flex-1 gap-10 p-8 bg-white rounded">
      <div class="grid gap-10 bg-white rounded" id="printable">
        <h2 class="text-5xl text-center title">Comprar:</h2>
        <ul class="grid gap-4 list-inside" id="print-list">
          <GiftsListItem
            v-for="gift in gifts"
            :key="`${gift.name}-${gift.owner}`"
            :gift="gift"
            :anonymous="true"
          />
        </ul>
      </div>
      <footer class="flex items-center justify-between">
        <button @click="showList = false">Cerrar</button>
        <button class="primary" @click="printList">Imprimir</button>
      </footer>
    </div>
  </dialog>

  <section
    class="flex flex-col flex-1 gap-16 p-8 bg-white text-neutral-900 rounded shadow-xl min-w-[500px] z-0"
    v-show="!showList"
  >
    <h1 className="text-5xl font-bold text-center title">Regalos:</h1>

    <div class="grid gap-12">
      <AddGiftForm
        v-model:currentGift="currentGift"
        v-model:gifts="gifts"
        v-model:showForm="showForm"
        :initialGift="INITIAL_GIFT"
      />

      <div v-if="!loadingData">
        <ul class="grid gap-4 list-inside" v-if="gifts.length">
          <GiftsListItem
            v-for="gift in gifts"
            :key="`${gift.name}-${gift.owner}`"
            :gift="gift"
            v-model:gifts="gifts"
            v-model:currentGift="currentGift"
            v-model:showForm="showForm"
          />
        </ul>
        <p v-else class="font-semibold text-center text-gray-500">
          No hay regalos Grinch! Agrega algo!
        </p>
      </div>
      <div v-else class="flex flex-col items-center mx-auto gap-y-4">
        <span class="loader"></span>
        <p class="text-2xl font-bold text-pink-500 animate-pulse">
          Cargando tus regalos !!!
        </p>
      </div>

      <GiftsListSummary :gifts="gifts" />
    </div>

    <footer class="grid gap-2" v-if="gifts.length">
      <button class="w-full danger" @click="handleDeleteAllGifts">
        Borrar todo
      </button>
      <button class="w-full" @click="previewList">Previsualizar</button>
    </footer>
  </section>
</template>

// denofresh/islands/app.tsx
import { useSignal } from '@preact/signals'
import { useEffect } from 'preact/hooks'
import api from '../api.ts'
import AddGiftForm from '../components/add-gift-form.tsx'
import GiftsListItem from '../components/gifts-list-item.tsx'
import GiftsListSummary from '../components/gifts-list-summary.tsx'
import Spinner from '../components/spinner.tsx'
import { GiftInterface } from '../types.ts'

const INITIAL_GIFT: GiftInterface = {
  id: '',
  name: '',
  quantity: 1,
  imageUrl: '',
  owner: '',
  price: 0,
}

export default function App() {
  const gifts = useSignal<GiftInterface[]>([])
  const currentGift = useSignal<GiftInterface>({
    ...INITIAL_GIFT,
  })
  const showForm = useSignal(false)
  const loadingData = useSignal(true)
  const showList = useSignal(false)

  useEffect(() => {
    loadingData.value = true

    api.gifts.list().then((_gifts) => {
      gifts.value = _gifts
      loadingData.value = false
    })
  }, [])

  function handleDeleteAllGifts() {
    gifts.value = []
    localStorage.removeItem('gifts')
  }

  function previewList() {
    window.scrollTo(0, 0)
    showList.value = true
  }

  function printList() {
    window.print()
  }

  return (
    <>
      {showList.value
        ? (
          <dialog className='absolute top-0 grid h-full w-full place-content-center bg-transparent text-neutral-900 shadow-xl'>
            <div className='flex flex-1 flex-col gap-10 rounded bg-white p-8'>
              <div className='grid gap-10 rounded bg-white' id='printable'>
                <h2 className='title text-center text-5xl'>Comprar:</h2>
                <ul className='grid list-inside gap-4' id='print-list'>
                  {gifts.value.map((gift: GiftInterface) => (
                    <GiftsListItem
                      key={`${gift.name}-${gift.owner}`}
                      anonymous
                      gift={gift}
                    />
                  ))}
                </ul>
              </div>
              <footer className='flex items-center justify-between'>
                <button type='button' onClick={() => showList.value = false}>
                  Cerrar
                </button>
                <button className='primary' type='button' onClick={printList}>
                  Imprimir
                </button>
              </footer>
            </div>
          </dialog>
        )
        : (
          <section className='z-0 flex min-w-[500px] flex-col gap-16 rounded bg-white p-8 text-neutral-900 shadow-xl'>
            <h1 className='title text-center text-5xl font-bold'>Regalos:</h1>

            <div className='grid gap-12'>
              <AddGiftForm
                initialGift={INITIAL_GIFT}
                currentGift={currentGift}
                gifts={gifts}
                showForm={showForm}
              />

              {loadingData.value ? <Spinner /> : (
                <div>
                  {gifts.value.length
                    ? (
                      <ul className='grid list-inside gap-4'>
                        {gifts.value.map((gift) => (
                          <GiftsListItem
                            key={`${gift.name}-${gift.owner}`}
                            gift={gift}
                            currentGift={currentGift}
                            gifts={gifts}
                            showForm={showForm}
                          />
                        ))}
                      </ul>
                    )
                    : (
                      <p className='text-center font-semibold text-gray-500'>
                        No hay regalos Grinch! Agrega algo!
                      </p>
                    )}
                </div>
              )}

              {gifts.value.length ? <GiftsListSummary gifts={gifts} /> : null}
            </div>

            {gifts.value.length
              ? (
                <footer className='grid gap-2'>
                  <button
                    className='danger w-full'
                    type='button'
                    onClick={handleDeleteAllGifts}
                  >
                    Borrar todo
                  </button>
                  <button
                    className='w-full'
                    type='button'
                    onClick={previewList}
                  >
                    Previsualizar
                  </button>
                </footer>
              )
              : null}
          </section>
        )}
    </>
  )
}
