// vue-ts/src/components/add-gift-form.vue
<template>
  <form class="grid gap-4" @submit.prevent="handleSubmit">
    <div class="grid gap-2" v-if="showForm">
      <div>
        <div class="flex items-center gap-x-2">
          <input
            type="text"
            placeholder="Agrega un regalo"
            v-model.trim="currentGift.name"
            class="flex-1 block w-full"
            name="name"
          />
          <button
            @click="
              currentGift.name =
                giftsSuggestions[
                  Math.floor(Math.random() * giftsSuggestions.length)
                ]
            "
            type="button"
          >
            Sorprenderme
          </button>
        </div>
        <p
          class="error-message"
          v-if="submitted && !textFieldRule.safeParse(currentGift.name).success"
        >
          El campo es requerido
        </p>
      </div>
      <div>
        <input
          type="text"
          placeholder="Url imagen"
          v-model.trim="currentGift.imageUrl"
          class="block w-full"
          name="imageUrl"
        />
        <p
          class="error-message"
          v-if="
            submitted && !textFieldRule.safeParse(currentGift.imageUrl).success
          "
        >
          El campo es requerido
        </p>
      </div>
      <div>
        <input
          type="text"
          placeholder="Propietario"
          v-model.trim="currentGift.owner"
          class="block w-full"
          name="owner"
        />
        <p
          class="error-message"
          v-if="
            submitted && !textFieldRule.safeParse(currentGift.owner).success
          "
        >
          El campo es requerido
        </p>
      </div>
      <div>
        <input
          type="number"
          placeholder="Precio"
          v-model.number="currentGift.price"
          class="block w-full"
          name="price"
        />
        <p
          class="error-message"
          v-if="
            submitted && !quantityFieldRule.safeParse(currentGift.price).success
          "
        >
          El numero debe ser un numero positivo
        </p>
      </div>
      <div>
        <input
          type="number"
          placeholder="Cantidad"
          v-model.number="currentGift.quantity"
          class="block w-full"
          name="quantity"
        />
        <p
          class="error-message"
          v-if="
            submitted &&
            !quantityFieldRule.safeParse(currentGift.quantity).success
          "
        >
          El numero debe ser un entero positivo
        </p>
      </div>
    </div>
    <footer
      class="flex"
      :class="[showForm ? 'justify-between' : 'justify-center']"
    >
      <button type="button" class="primary" @click="showForm = !showForm">
        {{ showForm ? 'Cerrar' : 'Agregar regalo' }}
      </button>
      <button type="submit" class="primary" v-if="showForm">
        {{ currentGift.id ? 'Editar' : 'Agregar' }}
      </button>
    </footer>
  </form>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { getGiftSchema } from '../schemas'
import { GiftInterface } from '../types'

const { initialGift } = defineProps<{
  initialGift: GiftInterface
}>()

const gifts = defineModel<GiftInterface[]>('gifts', {
  required: true
})
const currentGift = defineModel<GiftInterface>('currentGift', {
  required: true
})
const showForm = defineModel<boolean>('showForm', {
  required: true
})

const submitted = ref(false)

const giftsSuggestions = ['Pantalla', 'Celular', 'Laptop', 'Audifonos']
const { giftSchema, textFieldRule, quantityFieldRule } = getGiftSchema()

function handleSubmit() {
  submitted.value = true

  if (giftSchema.safeParse(currentGift.value).success) {
    if (currentGift.value.id) {
      const giftIndex = gifts.value.findIndex(
        ({ id: _id }) => _id === currentGift.value.id
      )
      gifts.value[giftIndex] = { ...currentGift.value }
    } else {
      gifts.value.push({ ...currentGift.value, id: currentGift.value.name })
    }

    localStorage.setItem('gifts', JSON.stringify(gifts.value))

    currentGift.value = { ...initialGift }
    submitted.value = false
  }
}
</script>

// sveltekit-ts/src/components/add-gift-form.svelte
<script lang="ts">
	import { getGiftSchema } from '../schemas';
	import type { GiftInterface } from '../types';

	export let initialGift: GiftInterface;
	export let gifts: GiftInterface[];
	export let currentGift: GiftInterface;
	export let showForm: boolean;

	let submitted = false;

	const giftsSuggestions = ['Pantalla', 'Celular', 'Laptop', 'Audifonos'];
	const { giftSchema, textFieldRule, quantityFieldRule } = getGiftSchema();

	function handleSubmit() {
		submitted = true;

		if (giftSchema.safeParse(currentGift).success) {
			if (currentGift.id) {
				const giftIndex = gifts.findIndex(({ id: _id }) => _id === currentGift.id);
				gifts[giftIndex] = { ...currentGift };
			} else {
				gifts.push({ ...currentGift, id: currentGift.name });
			}

			localStorage.setItem('gifts', JSON.stringify(gifts));

			currentGift = { ...initialGift };
			submitted = false;
		}
	}
</script>

<form class="grid gap-4" on:submit|preventDefault={handleSubmit}>
	{#if showForm}
		<div class="grid gap-2">
			<div>
				<div class="flex items-center gap-x-2">
					<input
						type="text"
						placeholder="Agrega un regalo"
						bind:value={currentGift.name}
						class="flex-1 block w-full"
						name="name"
					/>
					<button
						on:click={() =>
							(currentGift.name =
								giftsSuggestions[Math.floor(Math.random() * giftsSuggestions.length)])}
						type="button"
					>
						Sorprenderme
					</button>
				</div>
				{#if submitted && !textFieldRule.safeParse(currentGift.name).success}
					<p class="error-message">El campo es requerido</p>
				{/if}
			</div>
			<div>
				<input
					type="text"
					placeholder="Url imagen"
					bind:value={currentGift.imageUrl}
					class="block w-full"
					name="imageUrl"
				/>
				{#if submitted && !textFieldRule.safeParse(currentGift.imageUrl).success}
					<p class="error-message">El campo es requerido</p>
				{/if}
			</div>
			<div>
				<input
					type="text"
					placeholder="Propietario"
					bind:value={currentGift.owner}
					class="block w-full"
					name="owner"
				/>
				{#if submitted && !textFieldRule.safeParse(currentGift.owner).success}
					<p class="error-message">El campo es requerido</p>
				{/if}
			</div>
			<div>
				<input
					type="number"
					placeholder="Precio"
					bind:value={currentGift.price}
					class="block w-full"
					name="price"
				/>
				{#if submitted && !quantityFieldRule.safeParse(currentGift.price).success}
					<p class="error-message">El numero debe ser un numero positivo</p>
				{/if}
			</div>
			<div>
				<input
					type="number"
					placeholder="Cantidad"
					bind:value={currentGift.quantity}
					class="block w-full"
					name="quantity"
				/>
				{#if submitted && !quantityFieldRule.safeParse(currentGift.quantity).success}
					<p class="error-message">El numero debe ser un entero positivo</p>
				{/if}
			</div>
		</div>
	{/if}
	<footer class={`flex ${showForm ? 'justify-between' : 'justify-center'}`}>
		<button type="button" class="primary" on:click={() => (showForm = !showForm)}>
			{showForm ? 'Cerrar' : 'Agregar regalo'}
		</button>
		{#if showForm}
			<button type="submit" class="primary">
				{currentGift.id ? 'Editar' : 'Agregar'}
			</button>
		{/if}
	</footer>
</form>
